name: taylorjacobs
favicon: null
layout_spectrum: 0.7292346698231995
typography_spectrum: 0.33611012739129364
title: 'Taylor Jacobs Creative & Company'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8563351361081004
  lightness: 0.6883204975165427
  saturation: 0.7039205604232848
  rhythmicContrast: 0.8938832792919129
purpose: []
