name: taylorjacobs
favicon: null
layout_spectrum: 0.82485
typography_spectrum: 0.46034
title: 'Taylor Jacobs Creative & Company'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#55c2fc'
    - '#606060'
    - '#818181'
    - '#c9c9c9'
  brandStrength: 0.8563351361081004
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
