name: taylorjacobs
favicon: null
layout_spectrum: 1
typography_spectrum: 0.23834
title: 'Taylor Jacobs Creative & Company'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#55c2fc'
    - '#606060'
    - '#818181'
    - '#c9c9c9'
  brandStrength: 0.125
  lightness: 0.875
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
